### ISSUE TITLE
按照教程运行自己的trt模型报错

### ISSUE THREAD

**Issue by alvin0010** [stu-yzZ/yolov5infer#1]
## 在Windows上报错信息如下
```
[06/27/2024-09:58:52] [TRT] [I] Loaded engine size: 16 MiB
[06/27/2024-09:58:52] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +13, now: CPU 0, GPU 13 (MiB)
[06/27/2024-09:58:52] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +17, now: CPU 0, GPU 30 (MiB)
bingding: images (1, 3, 640, 640)
[06/27/2024-09:58:52] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
bingding: onnx::Sigmoid_369 (1, 3, 80, 80, 7)
[06/27/2024-09:58:52] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
bingding: onnx::Sigmoid_420 (1, 3, 40, 40, 7)
[06/27/2024-09:58:52] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
bingding: onnx::Sigmoid_468 (1, 3, 20, 20, 7)
[06/27/2024-09:58:52] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
bingding: output (1, 25200, 7)
[06/27/2024-09:58:52] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
[06/27/2024-09:58:52] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
[06/27/2024-09:58:52] [TRT] [W] The enqueue() method has been deprecated when used with engines built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. Please use enqueueV2() instead.
[06/27/2024-09:58:52] [TRT] [W] Also, the batchSize argument passed into this function has no effect on changing the input shapes. Please use setBindingDimensions() function to change input shapes instead.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 437, in run
    batch_image_raw, use_time,_ = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image_zeros(), vis=False)
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 181, in infer
    output = np.reshape(output, [self.batch_size, self.num_anchors, self.num_classes+5])
  File "<__array_function__ internals>", line 180, in reshape
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 134400 into shape (1,25200,7)
[06/27/2024-09:58:52] [TRT] [W] The enqueue() method has been deprecated when used with engines built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. Please use enqueueV2() instead.
[06/27/2024-09:58:52] [TRT] [W] Also, the batchSize argument passed into this function has no effect on changing the input shapes. Please use setBindingDimensions() function to change input shapes instead.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 437, in run
    batch_image_raw, use_time,_ = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image_zeros(), vis=False)
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 181, in infer
    output = np.reshape(output, [self.batch_size, self.num_anchors, self.num_classes+5])
  File "<__array_function__ internals>", line 180, in reshape
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 134400 into shape (1,25200,7)
[06/27/2024-09:58:52] [TRT] [W] The enqueue() method has been deprecated when used with engines built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. Please use enqueueV2() instead.
[06/27/2024-09:58:52] [TRT] [W] Also, the batchSize argument passed into this function has no effect on changing the input shapes. Please use setBindingDimensions() function to change input shapes instead.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 437, in run
    batch_image_raw, use_time,_ = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image_zeros(), vis=False)
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 181, in infer
    output = np.reshape(output, [self.batch_size, self.num_anchors, self.num_classes+5])
  File "<__array_function__ internals>", line 180, in reshape
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 134400 into shape (1,25200,7)
[06/27/2024-09:58:52] [TRT] [W] The enqueue() method has been deprecated when used with engines built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. Please use enqueueV2() instead.
[06/27/2024-09:58:52] [TRT] [W] Also, the batchSize argument passed into this function has no effect on changing the input shapes. Please use setBindingDimensions() function to change input shapes instead.
Exception in thread Thread-7:
Traceback (most recent call last):
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 437, in run
    batch_image_raw, use_time,_ = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image_zeros(), vis=False)
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 181, in infer
    output = np.reshape(output, [self.batch_size, self.num_anchors, self.num_classes+5])
  File "<__array_function__ internals>", line 180, in reshape
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 134400 into shape (1,25200,7)
[06/27/2024-09:58:52] [TRT] [W] The enqueue() method has been deprecated when used with engines built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. Please use enqueueV2() instead.
[06/27/2024-09:58:52] [TRT] [W] Also, the batchSize argument passed into this function has no effect on changing the input shapes. Please use setBindingDimensions() function to change input shapes instead.
Exception in thread Thread-9:
Traceback (most recent call last):
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 437, in run
    batch_image_raw, use_time,_ = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image_zeros(), vis=False)
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 181, in infer
    output = np.reshape(output, [self.batch_size, self.num_anchors, self.num_classes+5])
  File "<__array_function__ internals>", line 180, in reshape
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 134400 into shape (1,25200,7)
[06/27/2024-09:58:52] [TRT] [W] The enqueue() method has been deprecated when used with engines built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. Please use enqueueV2() instead.
[06/27/2024-09:58:52] [TRT] [W] Also, the batchSize argument passed into this function has no effect on changing the input shapes. Please use setBindingDimensions() function to change input shapes instead.
Exception in thread Thread-11:
Traceback (most recent call last):
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 437, in run
    batch_image_raw, use_time,_ = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image_zeros(), vis=False)
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 181, in infer
    output = np.reshape(output, [self.batch_size, self.num_anchors, self.num_classes+5])
  File "<__array_function__ internals>", line 180, in reshape
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 134400 into shape (1,25200,7)
[06/27/2024-09:58:52] [TRT] [W] The enqueue() method has been deprecated when used with engines built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. Please use enqueueV2() instead.
[06/27/2024-09:58:52] [TRT] [W] Also, the batchSize argument passed into this function has no effect on changing the input shapes. Please use setBindingDimensions() function to change input shapes instead.
Exception in thread Thread-13:
Traceback (most recent call last):
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 437, in run
    batch_image_raw, use_time,_ = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image_zeros(), vis=False)
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 181, in infer
    output = np.reshape(output, [self.batch_size, self.num_anchors, self.num_classes+5])
  File "<__array_function__ internals>", line 180, in reshape
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 134400 into shape (1,25200,7)
[06/27/2024-09:58:52] [TRT] [W] The enqueue() method has been deprecated when used with engines built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. Please use enqueueV2() instead.
[06/27/2024-09:58:52] [TRT] [W] Also, the batchSize argument passed into this function has no effect on changing the input shapes. Please use setBindingDimensions() function to change input shapes instead.
Exception in thread Thread-15:
Traceback (most recent call last):
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 437, in run
    batch_image_raw, use_time,_ = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image_zeros(), vis=False)
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 181, in infer
    output = np.reshape(output, [self.batch_size, self.num_anchors, self.num_classes+5])
  File "<__array_function__ internals>", line 180, in reshape
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 134400 into shape (1,25200,7)
[06/27/2024-09:58:52] [TRT] [W] The enqueue() method has been deprecated when used with engines built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. Please use enqueueV2() instead.
[06/27/2024-09:58:52] [TRT] [W] Also, the batchSize argument passed into this function has no effect on changing the input shapes. Please use setBindingDimensions() function to change input shapes instead.
Exception in thread Thread-17:
Traceback (most recent call last):
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 437, in run
    batch_image_raw, use_time,_ = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image_zeros(), vis=False)
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 181, in infer
    output = np.reshape(output, [self.batch_size, self.num_anchors, self.num_classes+5])
  File "<__array_function__ internals>", line 180, in reshape
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 134400 into shape (1,25200,7)
[06/27/2024-09:58:52] [TRT] [W] The enqueue() method has been deprecated when used with engines built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. Please use enqueueV2() instead.
[06/27/2024-09:58:52] [TRT] [W] Also, the batchSize argument passed into this function has no effect on changing the input shapes. Please use setBindingDimensions() function to change input shapes instead.
Exception in thread Thread-19:
Traceback (most recent call last):
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 437, in run
    batch_image_raw, use_time,_ = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image_zeros(), vis=False)
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 181, in infer
    output = np.reshape(output, [self.batch_size, self.num_anchors, self.num_classes+5])
  File "<__array_function__ internals>", line 180, in reshape
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 134400 into shape (1,25200,7)
[06/27/2024-09:58:56] [TRT] [W] The enqueue() method has been deprecated when used with engines built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. Please use enqueueV2() instead.
[06/27/2024-09:58:56] [TRT] [W] Also, the batchSize argument passed into this function has no effect on changing the input shapes. Please use setBindingDimensions() function to change input shapes instead.
Traceback (most recent call last):
  File ".\demo.py", line 149, in <module>
    vedio_detection()
  File ".\demo.py", line 118, in vedio_detection
    frame,time = trt_yolo(predictor, frame)
  File ".\demo.py", line 102, in trt_yolo
    res,img,time = process_image(predictor, img)
  File ".\demo.py", line 53, in process_image
    batch_image_raw, infer_time, results_batch = handle.infer(input_image, vis=vis)
  File "E:\Projects\temp_dir\yolov5infer\trt.py", line 181, in infer
    output = np.reshape(output, [self.batch_size, self.num_anchors, self.num_classes+5])
  File "<__array_function__ internals>", line 180, in reshape
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "D:\ProgramFiles\Miniconda3\envs\yolov5\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 134400 into shape (1,25200,7)
```

## 步骤复现
```

1、使用yolov5-6.1官方仓库export.py文件将训练好的pt转成onnx, 得到 my_model.onnx
python export.py --weights my_model.pt --include onnx

2、将.onnx转换为.trt模型
python totrt.py --onnx_path my_model.onnx --trt_path my_model.trt

3、修改trt.py中categories里面的类别为自己的类别,num_classes为自己的类别数量，engine_file_path改为自己trt模型的路径

4.运行trt.py
    运行报错

5、更改demo里面的文件路径
  运行也报错

```

大佬，这是啥原因呀

**Comment by stu-yzZ** [comment]
应该不用改trt.py中的代码，只需要改动demo中的代码即可。我看你报错实在trt.py这一个文件中，
File "E:\Projects\temp_dir\yolov5infer\trt.py", line 181, in infer
output = np.reshape(output, [self.batch_size, self.num_anchors, self.num_classes+5])
显示说 cannot reshape array of size 134400 into shape (1,25200,7)。意思是134400的output没法reshape成(1,25200,7)的[self.batch_size, self.num_anchors, self.num_classes+5]。

**Comment by alvin0010** [comment]
我用yolov5-6.1官方模型导出的onnx有四个输出，我看你的yolov5s.onnx文件只有一个输出，是不是这个原因，下图是你的onnx和我的onnx对比图

#### 你的onnx
![image](https://github.com/stu-yzZ/yolov5infer/assets/172792522/72184155-3413-4cea-a10a-a3ae28ba85d1)

#### 我的onnx
![image](https://github.com/stu-yzZ/yolov5infer/assets/172792522/39777aa0-30f8-41ce-b515-f2730f96ae5c)

**Comment by stu-yzZ** [comment]
我也不能确认 你可以将output打印出来看看 最近的错误行就可以定位到File "E:\Projects\temp_dir\yolov5infer\trt.py", line 181, in infer
output = np.reshape(output, [self.batch_size, self.num_anchors, self.num_classes+5])
这一句，你可以往上推一下，
或者你尝试先不要改类别，先跑，看是不是还有这个问题存在，如果没有问题，那就是类别不用改。

**Comment by alvin0010** [comment]
我打印了output上面一行输出的output值，没看出什么来。

我用你仓库自带的 yolov5s.onnx 用trtexec工具导出成trt格式文件，发现使用demo文件是可以跑的通的，如下图：

![image](https://github.com/stu-yzZ/yolov5infer/assets/172792522/9eaff8ed-cb9c-4892-8664-aa11cb72a543)

**Comment by stu-yzZ** [comment]
你在仔细捋一下 既然这个能跑通  你一点一点排查一下错误

**Comment by alvin0010** [comment]
🆗

**Comment by alvin0010** [comment]
你这个yolov5s是哪个版本的，我用6.1版本的s，导出成onnx的时候将4个输出变成一个1个输出，在你的代码上是能跑的通的，但是fps远不及你自带的onnx转成的trt模型。下图是我的修改了yolo.py代码后导出的onnx运行效果。
![image](https://github.com/stu-yzZ/yolov5infer/assets/172792522/04eeba7d-9c27-4a50-9d7e-0e89aaef3f3c)

**Comment by stu-yzZ** [comment]
时间有点久远 我忘记了 不好意思

**Comment by alvin0010** [comment]
我试了一下我自己训练的pt模型，如果在导出成onnx的时候是4个输出，则用你的代码就跑不出来，如果导出的onnx是1个输出，则用你这个代码就能跑的起来
